services:
  krakend:
    image: devopsfaith/krakend:latest
    ports:
      - 80:8080
    volumes:
      - ./krakend:/etc/krakend
    depends_on:
      rabbitmq:
        condition: service_healthy
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8080:8080
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
  keycloak-db:
    image: postgres:latest
    volumes:
      - ./keycloak/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/docker-volume:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "472"
    volumes:
      - ./grafana/docker-volume:/var/lib/grafana
