services:
  oathkeeper:
    image: oryd/oathkeeper:v0.38
    depends_on:
      - kratos
    ports:
      - 4455:4455
    command:
      serve -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    volumes:
      - ./kratos/config/oathkeeper:/etc/config/oathkeeper
    networks:
      - default
      - kratos-network

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.6.0-alpha.1
    environment:
      - PORT=4435
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
      - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
      - SECURITY_MODE=jwks
    restart: on-failure
    networks:
      - kratos-network

  kratos-migrate:
    image: oryd/kratos:v0.6.3-alpha.1
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./kratos/config/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - kratos-network

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v0.6.3-alpha.1
    restart: unless-stopped
    environment:
      - DSN=postgres://kratos:secret@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
      - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4455/.ory/kratos/public/
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - ./kratos/config/kratos:/etc/config/kratos
    networks:
      - kratos-network

  postgresd:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    volumes:
      - ./kratos/postgres-data:/var/lib/postgresql/data
    networks:
      - kratos-network

  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - ./krakend:/etc/krakend
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - default
      - grafana-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "472"
    volumes:
      - ./grafana/docker-volume:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    networks:
      - grafana-network

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - kratos-network

networks:
  kratos-network:
  grafana-network:
