services:
  krakend:
    image: devopsfaith/krakend:latest
    ports:
      - 8080:8080
    volumes:
      - ./krakend:/etc/krakend
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/docker-volume:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    user: "472"
    volumes:
      - ./grafana/docker-volume:/var/lib/grafana
