global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'oathkeeper'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['oathkeeper:9000']
  - job_name: 'krakend'
    scrape_interval: 15s
    static_configs:
      - targets: ['krakend:9091']
